services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PORT=3000
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    container_name: cogent-assignment
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: