services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PORT=3000
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - MINIO_ENDPOINT=localhost
        - MINIO_PORT=9000
        - MINIO_USE_SSL=false
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
        - MINIO_BUCKET_NAME=thumbnails
        - MINIO_PUBLIC_URL=http://localhost:9000
    container_name: cogent-assignment
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - minio

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

volumes:
  redis-data:
  minio-data:
